version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

    cooldown:
      default-days: 1

    groups:
      all-dependencies:
        update-types:
          - "major"
          - "minor"
          - "patch"

    open-pull-requests-limit: 5

    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
