packages:
  - .

minimumReleaseAgeExclude:
  - '@types/node@26.0.0'

onlyBuiltDependencies:
  - esbuild

overrides:
  acorn: 8.16.0
  baseline-browser-mapping: 2.10.35
  caniuse-lite: 1.0.30001797
  enhanced-resolve: 5.23.0
